### ISSUE TITLE
warning Uncaught TypeError: Cannot read properties of null (reading 'bufferedContent')

### ISSUE THREAD

**Issue by yanwuguangjun** [bony2023/react-terminal#171]
Uncaught TypeError: Cannot read properties of null (reading 'bufferedContent')
  

  "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^13.5.0",
    "@types/jest": "^27.5.2",
    "@types/node": "^16.11.47",
    "@types/react": "^18.0.17",
    "@types/react-dom": "^18.0.6",
    "axios": "^0.27.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "typescript": "^4.7.4",
    "web-vitals": "^2.1.4"

my react version  is  18.0

at  component version   v1.28  warning like 

```javascript
Uncaught TypeError: Cannot read properties of null (reading 'bufferedContent')
    at h (index.es.js:1:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
```

**Comment by BjornTheProgrammer** [comment]
Try to use yarn, I was having issues building using this project when using npm, maybe that will fix your issue.

**Comment by nadenf** [comment]
Getting this same issue with YARN as well.

**Comment by nadenf** [comment]
The issue for me was the TemplateContextProvider was not present. 

Maybe update Readme to indicate it is absolutely required ?
