### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'bufferedContent')

### ISSUE THREAD

**Issue by masoodhesami** [bony2023/react-terminal#260]
`      at logCapturedError (node_modules/react-dom/cjs/react-dom.development.js:18687:23)
      at update.callback (node_modules/react-dom/cjs/react-dom.development.js:18720:5)
      at callCallback (node_modules/react-dom/cjs/react-dom.development.js:13923:12)
      at commitUpdateQueue (node_modules/react-dom/cjs/react-dom.development.js:13944:9)
      at commitLayoutEffectOnFiber (node_modules/react-dom/cjs/react-dom.development.js:23391:13)
      at commitLayoutMountEffects_complete (node_modules/react-dom/cjs/react-dom.development.js:24688:9)
      at commitLayoutEffects_begin (node_modules/react-dom/cjs/react-dom.development.js:24674:7)`

what should i do ? all of my tests are fails when i render the react-terminal component !

**Comment by bony2023** [comment]
@masoodhesami Did you wrapped your main app entrypoint with `TerminalContextProvider`? More details in [README](https://github.com/bony2023/react-terminal#usage)

**Comment by masoodhesami** [comment]
Yes ! Still not working .. Sent from my iPhoneOn Dec 15, 2022, at 21:41, Bony Roopchandani ***@***.***> wrote:﻿
@masoodhesami Did you wrapped your main app entrypoint with TerminalContextProvider? More details in README

**Comment by bony2023** [comment]
@masoodhesami Can you share the snippet on how you are initializing the terminal?
